### ISSUE TITLE
Comments are wrong

### ISSUE THREAD

**Issue by Birdi7** [prostomarkeloff/aiogram-exam-bot#1]
Hello. ASAIK the comments in the beginning of [handlers_callback_query.py](bot/commands/handlers_callback_query.py) is wrong. According to the name, this file shouldn't contain handlers of the data from reply keyboards. If I am wrong, then the comments in the [reply_keyboards.py](bot/plugins/reply_keyboards.py) should be changed as they state the same. Thank you!

**Comment by prostomarkeloff** [comment]
[Fixed. ](https://github.com/prostomarkeloff/aiogram-exam-bot/commit/f00797555a349fe2ea8344ed80ef8e413ddbe359)
